/**
 * @file horizontal_drift.h
 * @author Alberto Vazquez
 * @brief Short-horizon inertial brake for uncommanded horizontal drift.
 *
 * @details FlightControl calls this estimator only from the fresh-IMU control
 * path. It rotates body acceleration into a level horizontal frame, removes
 * gravity, applies deadbands/leakage, integrates acceleration into velocity,
 * and converts estimated velocity into small roll/pitch setpoint corrections.
 * All acceleration values use m/s^2, velocity uses m/s, position uses m, and
 * corrections use degrees. The compile-time switch below is currently 0U, so
 * every correction is forced to zero without removing the API or telemetry.
 * @version 1.1.0
 * @date 2026-09-29
 */

#ifndef INCLUDE_HORIZONTAL_DRIFT_H_
#define INCLUDE_HORIZONTAL_DRIFT_H_

#include "lsm6ds.h"

/**
 * Compile-time master switch.
 * 1U enables the estimator and brake; 0U keeps the API present but forces the
 * runtime status to DISABLED and every correction to zero degrees.
 */
#define HORIZONTAL_DRIFT_COMPENSATION_ENABLED  0U

/** Result of the most recent initialization, update, or explicit reset. */
typedef enum
{
    /** Update completed and the public estimates/corrections are current. */
    HORIZONTAL_DRIFT_STATUS_OK = 0,
    /** A detected motion settled and the local integration origin was reset. */
    HORIZONTAL_DRIFT_STATUS_RESET,
    /** Gating conditions are false, so estimates and corrections are zero. */
    HORIZONTAL_DRIFT_STATUS_INACTIVE,
    /** The compile-time or runtime enable switch is false. */
    HORIZONTAL_DRIFT_STATUS_DISABLED,
    /** A required pointer/value is NULL, non-finite, or outside timing limits. */
    HORIZONTAL_DRIFT_STATUS_INVALID_ARGUMENT,
    /** One or more configuration values violate the documented ranges. */
    HORIZONTAL_DRIFT_STATUS_INVALID_CONFIG,
    /** Update was called before HorizontalDrift_Init completed successfully. */
    HORIZONTAL_DRIFT_STATUS_NOT_INITIALIZED
} HorizontalDrift_Status_t;

/** Two-dimensional value in the local horizontal aircraft frame. */
typedef struct
{
    /** Forward axis component; unit depends on the containing structure. */
    float32_t x;
    /** Empirically validated left-positive axis; unit depends on the container. */
    float32_t y;
} HorizontalDrift_Vector2f_t;

/** Tunable parameters copied into each controller instance at initialization. */
typedef struct
{
    /** Runtime enable switch; false forces zero correction. Unit: boolean. */
    bool enabled;
    /** First-order acceleration low-pass cutoff. Unit: hertz. */
    float32_t acceleration_filter_cutoff_hz;
    /** Symmetric acceleration noise deadband. Unit: metres/second squared. */
    float32_t acceleration_deadband_mps2;
    /** Leaky velocity-integrator time constant. Unit: seconds. */
    float32_t velocity_leak_time_s;
    /** Leaky displacement-integrator time constant. Unit: seconds. */
    float32_t displacement_leak_time_s;
    /** Position feedback gain used to request braking tilt. Unit: degrees/metre. */
    float32_t displacement_gain_deg_per_m;
    /** Velocity feedback gain used to request braking tilt. Unit: degrees/(m/s). */
    float32_t velocity_gain_deg_per_mps;
    /** Absolute roll/pitch trim limit generated by this module. Unit: degrees. */
    float32_t maximum_correction_deg;
    /** Minimum normalized throttle that permits estimation/control. Unit: 0...1. */
    float32_t minimum_throttle;
    /** Acceleration norm that latches motion detection. Unit: m/s². */
    float32_t motion_acceleration_threshold_mps2;
    /** Velocity norm that latches motion detection. Unit: m/s. */
    float32_t motion_velocity_threshold_mps;
    /** Maximum acceleration norm considered settled. Unit: m/s². */
    float32_t settled_acceleration_threshold_mps2;
    /** Maximum estimated speed considered settled. Unit: m/s. */
    float32_t settled_velocity_threshold_mps;
    /** Continuous settled duration required before reset. Unit: seconds. */
    float32_t settled_time_s;
    /** Absolute per-axis velocity estimate limit. Unit: m/s. */
    float32_t maximum_velocity_mps;
    /** Absolute per-axis local displacement estimate limit. Unit: metres. */
    float32_t maximum_displacement_m;
} HorizontalDrift_Config_t;

/** Public values intended for FlightControl, CCS Watch, and telemetry. */
typedef struct
{
    /** Gravity-compensated, filtered horizontal acceleration. Unit: m/s². */
    HorizontalDrift_Vector2f_t acceleration_mps2;
    /** Bounded leaky integral of acceleration. Unit: m/s. */
    HorizontalDrift_Vector2f_t velocity_mps;
    /** Bounded leaky integral of velocity from the local origin. Unit: metres. */
    HorizontalDrift_Vector2f_t displacement_m;
    /** Angle added to the roll stick setpoint. Unit: degrees. */
    float32_t roll_correction_deg;
    /** Angle added to the pitch stick setpoint. Unit: degrees. */
    float32_t pitch_correction_deg;
    /** True while every safety/gating condition permits the estimator to run. */
    bool active;
    /** Latched true after acceleration or velocity exceeds its motion threshold. */
    bool motion_detected;
    /** Number of automatic settled-motion resets since initialization. */
    uint32_t reset_count;
} HorizontalDrift_Output_t;

/** One independent short-horizon estimator/controller instance. */
typedef struct
{
    /** True only after successful HorizontalDrift_Init. */
    bool initialized;
    /** Instance-specific copy of every tuning parameter and its units. */
    HorizontalDrift_Config_t config;
    /** Public estimator/control values consumed by the flight controller. */
    HorizontalDrift_Output_t output;
    /** Most recent API result, observable from CCS. */
    HorizontalDrift_Status_t last_status;

    /* Private runtime state. */
    /** Stationary startup accelerometer mean. Unit: m/s² in IMU body axes. */
    LSM6DS_Vector3f_t level_acceleration_mps2;
    /** Low-pass state before applying the acceleration deadband. Unit: m/s². */
    HorizontalDrift_Vector2f_t filtered_acceleration_mps2;
    /** Previous deadbanded acceleration for trapezoidal integration. Unit: m/s². */
    HorizontalDrift_Vector2f_t previous_acceleration_mps2;
    /** Time continuously below both settled thresholds. Unit: seconds. */
    float32_t settled_elapsed_s;
    /** Prevents filtering against an artificial zero on the first active sample. */
    bool filter_initialized;
    /** Prevents trapezoidal integration from using an invalid previous sample. */
    bool integration_initialized;
} HorizontalDrift_Data_t;

/**
 * Initialize an instance.
 * @param data Writable estimator/controller instance.
 * @param config Optional configuration; NULL selects the documented defaults.
 * @param level_acceleration_mps2 Stationary startup mean in m/s².
 * @return OK on success or an argument/configuration error.
 */
HorizontalDrift_Status_t HorizontalDrift_Init(
    HorizontalDrift_Data_t *data,
    const HorizontalDrift_Config_t *config,
    const LSM6DS_Vector3f_t *level_acceleration_mps2);

/**
 * Clear the local velocity/displacement origin and commanded correction.
 * @param data Initialized instance to clear. A NULL pointer is ignored.
 * @return Nothing.
 */
void HorizontalDrift_Reset(HorizontalDrift_Data_t *data);

/**
 * Update the short-horizon estimator and braking-angle command.
 * @param data Initialized estimator/controller instance.
 * @param acceleration_mps2 Latest raw physical IMU acceleration in m/s².
 * @param roll_deg Current level-referenced roll angle in degrees.
 * @param pitch_deg Current level-referenced pitch angle in degrees.
 * @param dt_s Elapsed time represented by the IMU sample in seconds.
 * @param throttle Normalized throttle command in the range 0...1.
 * @param command_centered True only when roll, pitch, and yaw sticks are idle.
 * @param heading_stable True while magnetic heading hold fixes the local axes.
 * @param acceleration_trusted True when the flight controller accepts |accel|.
 * @return Current module status; non-OK gating states command zero correction.
 */
HorizontalDrift_Status_t HorizontalDrift_Update(
    HorizontalDrift_Data_t *data,
    const LSM6DS_Vector3f_t *acceleration_mps2,
    float32_t roll_deg,
    float32_t pitch_deg,
    float32_t dt_s,
    float32_t throttle,
    bool command_centered,
    bool heading_stable,
    bool acceleration_trusted);

#endif /* INCLUDE_HORIZONTAL_DRIFT_H_ */
