/**
 * @file lis2mdl.c
 * @author Alberto Vazquez
 * @brief LIS2MDL identification, configuration, and magnetic-field reading.
 *
 * @details Engineering execution overview:
 * - Init proves that an LIS2MDL is present at address 0x1E and configures it.
 * - Update reads X/Y/Z signed counts when the sensor reports fresh data.
 * - convert_and_calibrate() converts counts to microteslas, removes hard-iron
 *   offset, applies scale correction, and maps sensor axes into aircraft FRD.
 * - The module only measures magnetic field. mag_heading.c turns that vector
 *   into a tilt-compensated heading for the yaw controller.
 * @version 1.1.0
 * @date 2026-09-29
 */

#include <math.h>
#include <string.h>

#include "lis2mdl.h"
#include "i2c0_drone.h"
#include "systick.h"

/* Fixed LIS2MDL 7-bit I2C address and expected identity value. */
#define LIS2MDL_I2C_ADDRESS          0x1EU
#define LIS2MDL_WHO_AM_I_VALUE       0x40U

/* LIS2MDL register addresses used by this application. */
#define REG_WHO_AM_I                 0x4FU
#define REG_CFG_A                    0x60U
#define REG_CFG_B                    0x61U
#define REG_CFG_C                    0x62U
#define REG_STATUS                   0x67U
#define REG_OUT_X_L                  0x68U

/* Temperature compensation, 50 Hz ODR, continuous conversion. */
#define CFG_A_50_HZ_CONTINUOUS       0x88U
/* Default offset-cancellation behavior selected for CFG_REG_B. */
#define CFG_B_DEFAULT                0x00U
/* Block-data-update prevents mixed samples during a six-byte burst. */
#define CFG_C_BLOCK_DATA_UPDATE      0x10U
/* Readback masks contain only implemented/configurable register bits. */
#define CFG_A_VERIFY_MASK            0x9FU
#define CFG_B_VERIFY_MASK            0x1FU
#define CFG_C_VERIFY_MASK            0x7FU

/* Status bits for complete XYZ availability and unread-sample replacement. */
#define STATUS_NEW_XYZ_MASK          0x08U
#define STATUS_XYZ_OVERRUN_MASK      0x80U
/* LIS2MDL scale at its fixed full-scale range, in microtesla per count. */
#define MAGNETIC_FIELD_UT_PER_LSB    0.15f

/*
 * Calibration obtained with the complete aircraft assembled and its motors
 * stopped. The 3x3 matrix maps bias-corrected sensor microtesla directly to
 * the aircraft FRD frame. Its orientation component is diag(-1, -1, +1).
 */
static const LIS2MDL_Calibration_t g_flight_calibration = {
    /* hard_iron_bias_sensor_ut: constant field measured in sensor axes. */
    { -42.635213f, -32.064639f, -17.395767f },
    /* sensor_to_body: soft-iron correction and sensor-to-airframe rotation. */
    {
        { -1.06057358f, -0.00184916f, -0.01607728f },
        { -0.00184916f, -0.96908406f, -0.00021050f },
        {  0.01607728f,  0.00021050f,  0.97321318f }
    },
    36.167750f /* Reference local field magnitude, in microtesla. */
};

/**
 * @brief Convert raw LIS2MDL counts into calibrated aircraft-frame magnetic field.
 * @param data Instance providing calibration/axis mapping and receiving results.
 * @param raw Signed sensor-axis samples [counts].
 * @return Nothing; sensor_field_ut, body_field_ut, and magnitude are updated [uT].
 */
static void convert_and_calibrate(LIS2MDL_Data_t *data,
                                  const LIS2MDL_RawVector3_t *raw)
{
    LIS2MDL_Vector3f_t centered; /* Bias-removed sensor field, in microtesla. */
    /* 3x3 calibration matrix mapping sensor axes to aircraft FRD axes. */
    float32_t (*matrix)[3] = data->calibration.sensor_to_body;

    /* Convert signed ADC counts to the sensor-frame magnetic field. */
    data->sample.sensor_field_ut.x =
        (float32_t)raw->x * MAGNETIC_FIELD_UT_PER_LSB;
    data->sample.sensor_field_ut.y =
        (float32_t)raw->y * MAGNETIC_FIELD_UT_PER_LSB;
    data->sample.sensor_field_ut.z =
        (float32_t)raw->z * MAGNETIC_FIELD_UT_PER_LSB;

    /* Remove the constant hard-iron field generated by the assembled aircraft. */
    centered.x = data->sample.sensor_field_ut.x -
                 data->calibration.hard_iron_bias_sensor_ut.x;
    centered.y = data->sample.sensor_field_ut.y -
                 data->calibration.hard_iron_bias_sensor_ut.y;
    centered.z = data->sample.sensor_field_ut.z -
                 data->calibration.hard_iron_bias_sensor_ut.z;

    /* Apply full matrix calibration and rotate into forward-right-down axes. */
    data->sample.body_field_ut.x =
        (matrix[0][0] * centered.x) +
        (matrix[0][1] * centered.y) +
        (matrix[0][2] * centered.z);
    data->sample.body_field_ut.y =
        (matrix[1][0] * centered.x) +
        (matrix[1][1] * centered.y) +
        (matrix[1][2] * centered.z);
    data->sample.body_field_ut.z =
        (matrix[2][0] * centered.x) +
        (matrix[2][1] * centered.y) +
        (matrix[2][2] * centered.z);
    /* Magnitude is orientation-independent and supports magnetic anomaly checks. */
    data->sample.body_field_magnitude_ut = sqrtf(
        (data->sample.body_field_ut.x * data->sample.body_field_ut.x) +
        (data->sample.body_field_ut.y * data->sample.body_field_ut.y) +
        (data->sample.body_field_ut.z * data->sample.body_field_ut.z));
}

/** Translate a shared I2C0 status into the corresponding LIS2MDL status. */
static LIS2MDL_Status_t status_from_i2c(I2C0_Status_t status)
{
    /* Translate transport errors without discarding their cause. */
    switch(status)
    {
        case I2C_OK:          return LIS2MDL_STATUS_OK;
        case I2C_ERR_ARB:     return LIS2MDL_STATUS_I2C_ARBITRATION;
        case I2C_ERR_ADDR:    return LIS2MDL_STATUS_I2C_ADDRESS;
        case I2C_ERR_DATA:    return LIS2MDL_STATUS_I2C_DATA;
        case I2C_ERR_TIMEOUT: return LIS2MDL_STATUS_I2C_TIMEOUT;
        default:              return LIS2MDL_STATUS_INVALID_ARGUMENT;
    }
}

/** Return true for statuses caused by NACK, timeout, or another I2C bus failure. */
static bool is_bus_error(LIS2MDL_Status_t status)
{
    return (status >= LIS2MDL_STATUS_I2C_ARBITRATION) &&
           (status <= LIS2MDL_STATUS_I2C_TIMEOUT);
}

/** Store the last status, count communication failures, and return status unchanged. */
static LIS2MDL_Status_t finish(LIS2MDL_Data_t *data,
                               LIS2MDL_Status_t status)
{
    /* Publish the last result and count only actual I2C communication faults. */
    if(data != NULL)
    {
        data->last_status = status;
        if(is_bus_error(status))
        {
            data->communication_error_count++;
        }
    }
    return status;
}

/** Read length sequential bytes beginning at one LIS2MDL register address. */
static LIS2MDL_Status_t read_register(uint8_t reg,
                                      uint8_t *buffer,
                                      uint32_t length)
{
    return status_from_i2c(I2C0_WriteRead(LIS2MDL_I2C_ADDRESS,
                                          reg,
                                          buffer,
                                          length));
}

/** Write one byte value to one LIS2MDL register and report ACK/error status. */
static LIS2MDL_Status_t write_register(uint8_t reg, uint8_t value)
{
    return status_from_i2c(I2C0_WriteWrite(LIS2MDL_I2C_ADDRESS,
                                           reg,
                                           value));
}

/** Write one configuration byte, read it back, and compare only bits selected by mask. */
static LIS2MDL_Status_t write_and_verify(uint8_t reg,
                                         uint8_t value,
                                         uint8_t mask)
{
    uint8_t readback = 0U;     /* Register contents read after writing. */
    LIS2MDL_Status_t status;   /* Communication or comparison result. */

    status = write_register(reg, value);
    if(status == LIS2MDL_STATUS_OK)
    {
        status = read_register(reg, &readback, 1U);
    }
    if((status == LIS2MDL_STATUS_OK) &&
       ((readback & mask) != (value & mask)))
    {
        status = LIS2MDL_STATUS_CONFIGURATION_ERROR;
    }
    return status;
}

/** Program continuous 50 Hz operation, block-data update, and required filtering. */
static LIS2MDL_Status_t configure_device(void)
{
    /* Register/value/mask entries applied and verified in order. */
    static const struct
    {
        uint8_t reg;   /**< Eight-bit LIS2MDL register address. */
        uint8_t value; /**< Eight-bit value that will be written. */
        uint8_t mask;  /**< Implemented bits compared during readback. */
    } configuration[] = {
        { REG_CFG_A, CFG_A_50_HZ_CONTINUOUS,  CFG_A_VERIFY_MASK },
        { REG_CFG_B, CFG_B_DEFAULT,           CFG_B_VERIFY_MASK },
        { REG_CFG_C, CFG_C_BLOCK_DATA_UPDATE, CFG_C_VERIFY_MASK }
    };
    LIS2MDL_Status_t status = LIS2MDL_STATUS_OK; /* Current table-row result. */
    uint32_t i; /* Configuration-table index. */

    for(i = 0U; i < (sizeof(configuration) / sizeof(configuration[0])); i++)
    {
        status = write_and_verify(configuration[i].reg,
                                  configuration[i].value,
                                  configuration[i].mask);
        if(status != LIS2MDL_STATUS_OK)
        {
            return status;
        }
    }

    /* One 50 Hz conversion period ensures the first status poll is coherent. */
    Delay_ms(20U);
    return LIS2MDL_STATUS_OK;
}

/**
 * @brief Detect, reset, configure, and prepare one LIS2MDL instance.
 * @param data Destination state containing identity, calibration, sample, and counters.
 * @return OK or the exact WHO_AM_I, configuration, argument, or I2C failure.
 */
LIS2MDL_Status_t LIS2MDL_Init(LIS2MDL_Data_t *data)
{
    uint8_t identity = 0U;    /* WHO_AM_I register returned by the slave. */
    LIS2MDL_Status_t status;  /* Current initialization stage result. */

    if(data == NULL)
    {
        return LIS2MDL_STATUS_INVALID_ARGUMENT;
    }

    /* Establish deterministic state before any bus access occurs. */
    memset(data, 0, sizeof(*data));
    data->address = LIS2MDL_I2C_ADDRESS;
    data->calibration = g_flight_calibration;
    data->last_status = LIS2MDL_STATUS_NOT_INITIALIZED;

    status = read_register(REG_WHO_AM_I, &identity, 1U);
    if(status == LIS2MDL_STATUS_I2C_ADDRESS)
    {
        return finish(data, LIS2MDL_STATUS_DEVICE_NOT_FOUND);
    }
    if(status != LIS2MDL_STATUS_OK)
    {
        return finish(data, status);
    }

    data->device_id = identity;
    if(identity != LIS2MDL_WHO_AM_I_VALUE)
    {
        return finish(data, LIS2MDL_STATUS_DEVICE_NOT_FOUND);
    }

    status = configure_device();
    if(status != LIS2MDL_STATUS_OK)
    {
        return finish(data, status);
    }

    data->initialized = true;
    return finish(data, LIS2MDL_STATUS_OK);
}

/**
 * @brief Acquire and publish one magnetic sample when the data-ready bit is set.
 * @param data Initialized instance receiving counts, field [uT], time [us], and flags.
 * @return OK for a fresh sample, NO_NEW_DATA while waiting, or an error status.
 */
LIS2MDL_Status_t LIS2MDL_Update(LIS2MDL_Data_t *data)
{
    uint8_t status_register;      /* Data-ready and overrun flags. */
    uint8_t raw_bytes[6];         /* Packed X, Y, and Z little-endian samples. */
    LIS2MDL_RawVector3_t raw;     /* Signed sensor counts for all three axes. */
    LIS2MDL_Status_t status;      /* Current I2C/driver operation result. */

    if(data == NULL)
    {
        return LIS2MDL_STATUS_INVALID_ARGUMENT;
    }
    data->sample.fresh = false;
    if(!data->initialized)
    {
        data->sample.valid = false;
        return finish(data, LIS2MDL_STATUS_NOT_INITIALIZED);
    }

    status = read_register(REG_STATUS, &status_register, 1U);
    if(status != LIS2MDL_STATUS_OK)
    {
        data->sample.valid = false;
        return finish(data, status);
    }

    data->sample.status_register = status_register;
    data->sample.overrun =
        (status_register & STATUS_XYZ_OVERRUN_MASK) != 0U;
    if(data->sample.overrun && (data->data_overrun_count < 0xFFFFFFFFU))
    {
        data->data_overrun_count++;
    }
    if((status_register & STATUS_NEW_XYZ_MASK) == 0U)
    {
        return finish(data, LIS2MDL_STATUS_NO_NEW_DATA);
    }

    status = read_register(REG_OUT_X_L, raw_bytes, sizeof(raw_bytes));
    if(status != LIS2MDL_STATUS_OK)
    {
        data->sample.valid = false;
        return finish(data, status);
    }

    /* Reconstruct the three signed 16-bit little-endian measurements. */
    raw.x = (int16_t)((uint16_t)raw_bytes[0] |
                      ((uint16_t)raw_bytes[1] << 8U));
    raw.y = (int16_t)((uint16_t)raw_bytes[2] |
                      ((uint16_t)raw_bytes[3] << 8U));
    raw.z = (int16_t)((uint16_t)raw_bytes[4] |
                      ((uint16_t)raw_bytes[5] << 8U));

    /* Convert, calibrate, timestamp, and atomically mark this sample usable. */
    data->sample.raw = raw;
    convert_and_calibrate(data, &raw);
    data->sample.timestamp_us = Timebase_GetMicroseconds();
    data->sample.sequence++;
    data->sample.valid = true;
    data->sample.fresh = true;
    return finish(data, LIS2MDL_STATUS_OK);
}
